require("ytconfig.plugins-setup")
require("ytconfig.core.options")
require("ytconfig.core.keymaps")
require("ytconfig.core.colorscheme")

-- 下面是插件有关配置
require("ytconfig.plugins.comment")
require("ytconfig.plugins.nvim-tree")
require("ytconfig.plugins.lualine")
require("ytconfig.plugins.telescope")
require("ytconfig.plugins.nvim-cmp")
require("ytconfig.plugins.lsp.mason")
require("ytconfig.plugins.lsp.lspsaga")
require("ytconfig.plugins.lsp.lspconfig")
require("ytconfig.plugins.lsp.null-ls")
require("ytconfig.plugins.autopairs")
require("ytconfig.plugins.treesitter")
require("ytconfig.plugins.gitsigns")
